package model.transaction;

public enum TransactionAttributeValue {
    TRANSACTION_TYPE_DEBIT,
    TRANSACTION_TYPE_CREDIT,
    TRANSACTION_TYPE_MEMO,
    TRANSACTION_METHOD_PURCHASE,
    TRANSACTION_METHOD_CASH,
    TRANSACTION_METHOD_PAYMENT,
    TRANSACTION_METHOD_FEES,
    TRANSACTION_CURRENCY_GBP,
    TRANSACTION_CURRENCY_EURO,
    TRANSACTION_CURRENCY_DOLLOR
} 
