package com.billing.config.buckets;

public enum BucketCode {
    PRINCIPAL,
    ACCRUED_INTEREST,
    OVERALL_AREGATE_BALANCE,
    CYCLE_AGGREGATE_BALANCE,
    LAST_BILL_WAIVED_INTEREST,
    LAST_BILL_DEFERRED_INTEREST,
    LAST_BILL_ACCRUED_INTEREST,
    LAST_BILL_PRINCIPAL,
    BILLED_INTEREST,
    CASH_ADVANCE_FEE,
    LATE_FEE,
    MEMBERSHIP_FEE,
    CURRENCY_CONVERSION_FEE
}
